---

- name: Restart service
  command: docker-compose up -d
  args:
    chdir: "{{ loki.dir }}"
  listen: "restart loki"

- name: Restart syslog
  systemd:
    name: rsyslog
    state: restarted
  listen: "restart syslog"
