---

- name: Converge
  hosts: all
  become: true

  vars:
    env: develop

    services_dir: /opt/services

    private_network: "{{ ansible_eth0['ipv4'] }}"

    loki:
      dir: "{{ services_dir }}/loki"

      server:
        enabled: true
        host: "{{ private_network.address }}"
        port: 3100

        container:
          image: grafana/loki:v1.3.0
          name: loki
          dns: "{{ private_network.address }}"
          network: ""
          restart: always

          syslog:
            enabled: false
            host: unixgram:///dev/log
            tag: loki

        exporter:
          host: "{{ private_network.address }}"
          port: 3100

      promtail:
        host: "{{ private_network.address }}"
        port: 9080

        loki:
          host: "{{ private_network.address }}"
          port: 3100

        syslog:
          host: "{{ private_network.address }}"
          port: 1514

        jobs:
          syslog:
            labels:
              tier: "{{ env }}"
          static: []

        container:
          image: grafana/promtail:v1.3.0
          name: promtail
          dns: "{{ private_network.address }}"
          network: ""
          restart: always

          syslog:
            enabled: false
            host: unixgram:///dev/log
            tag: promtail

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

  tasks:
    - name: Install test requirements
      apt: name=curl
